console.error('populate serviceAccountKey.js with your firebase service account keys - https://firebase.google.com/docs/admin/setup')

// const config = {
//   "type": ...,
//   "project_id": ...,
//   "private_key_id": ...
//   "private_key": "-----BEGIN PRIVATE KEY-----...",
//   "client_email": ...,
//   "client_id": ...,
//   "auth_uri": ...
//   "token_uri": ...
//   "auth_provider_x509_cert_url": ...
//   "client_x509_cert_url": ...
// }
// module.exports = config